/*
 * Generated by dtrace(1M).
 */

#ifndef	_OPUS_PROBES_H
#define	_OPUS_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define OPUSBUFFERS_STABILITY "___dtrace_stability$opusBuffers$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define OPUSBUFFERS_TYPEDEFS "___dtrace_typedefs$opusBuffers$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	OPUSBUFFERS_OPUSBUFFER_STATS(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " OPUSBUFFERS_TYPEDEFS); \
	__dtrace_probe$opusBuffers$opusbuffer_stats$v1$6c6f6e67$6c6f6e67$6c6f6e67$6c6f6e67(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " OPUSBUFFERS_STABILITY); \
} while (0)
#define	OPUSBUFFERS_OPUSBUFFER_STATS_ENABLED() \
	({ int _r = __dtrace_isenabled$opusBuffers$opusbuffer_stats$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$opusBuffers$opusbuffer_stats$v1$6c6f6e67$6c6f6e67$6c6f6e67$6c6f6e67(long, long, long, long);
extern int __dtrace_isenabled$opusBuffers$opusbuffer_stats$v1(void);

#else

#define	OPUSBUFFERS_OPUSBUFFER_STATS(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	OPUSBUFFERS_OPUSBUFFER_STATS_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _OPUS_PROBES_H */
