/*
 * Generated by dtrace(1M).
 */

#ifndef	_XFLEXPROBES_H
#define	_XFLEXPROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define XFLEX_STABILITY "___dtrace_stability$xFlex$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define XFLEX_TYPEDEFS "___dtrace_typedefs$xFlex$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	XFLEX_INTEGERVALUERANGE(arg0) \
do { \
	__asm__ volatile(".reference " XFLEX_TYPEDEFS); \
	__dtrace_probe$xFlex$integerValueRange$v1$696e74(arg0); \
	__asm__ volatile(".reference " XFLEX_STABILITY); \
} while (0)
#define	XFLEX_INTEGERVALUERANGE_ENABLED() \
	({ int _r = __dtrace_isenabled$xFlex$integerValueRange$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$xFlex$integerValueRange$v1$696e74(int);
extern int __dtrace_isenabled$xFlex$integerValueRange$v1(void);

#else

#define	XFLEX_INTEGERVALUERANGE(arg0) \
do { \
	} while (0)
#define	XFLEX_INTEGERVALUERANGE_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _XFLEXPROBES_H */
