// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import CoreGraphics;
@import Dispatch;
#endif

#import <xFlexAPI/xFlexAPI.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC8xFlexAPI11AudioStream")
@interface AudioStream : NSObject
@property (nonatomic, readonly) NSInteger rxLostPacketCount;
- (BOOL)requestAudioStream SWIFT_WARN_UNUSED_RESULT;
- (void)removeAudioStream;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class Slice;

@interface AudioStream (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) NSInteger daxChannel;
@property (nonatomic) NSInteger daxClients;
@property (nonatomic) BOOL inUse;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic) NSInteger port;
@property (nonatomic) BOOL radioAck;
@property (nonatomic) NSInteger rxGain;
@property (nonatomic, strong) Slice * _Nullable slice;
@property (nonatomic, copy) NSString * _Nonnull streamId;
@end


SWIFT_CLASS("_TtC8xFlexAPI3Cwx")
@interface Cwx : NSObject
@property (nonatomic, copy) void (^ _Nullable messageQueuedEventHandler)(NSInteger, NSInteger);
@property (nonatomic, copy) void (^ _Nullable charSentEventHandler)(NSInteger);
@property (nonatomic, copy) void (^ _Nullable eraseSentEventHandler)(NSInteger, NSInteger);
- (void)clearBuffer;
- (void)eraseWithNumberOfChars:(NSInteger)numberOfChars;
/// Save the specified Cwx Macro and tell the Radio (hardware)
/// \code
/// NOTE:
///     Macros are numbered 0..<kMaxNumberOfMacros internally
///     Macros are numbered 1...kMaxNumberOfMacros in commands
///
/// \endcode\param index the index of the macro
///
/// \param msg the text of the macro
///
///
/// returns:
/// true if found, false otherwise
- (BOOL)saveMacroWithIndex:(NSInteger)index msg:(NSString * _Nonnull)msg SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Cwx (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) NSInteger delay;
@property (nonatomic) BOOL qskEnabled;
@property (nonatomic) NSInteger speed;
@end


SWIFT_CLASS("_TtC8xFlexAPI9Equalizer")
@interface Equalizer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Equalizer (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) BOOL eqEnabled;
@property (nonatomic) NSInteger level63Hz;
@property (nonatomic) NSInteger level125Hz;
@property (nonatomic) NSInteger level250Hz;
@property (nonatomic) NSInteger level500Hz;
@property (nonatomic) NSInteger level1000Hz;
@property (nonatomic) NSInteger level2000Hz;
@property (nonatomic) NSInteger level4000Hz;
@property (nonatomic) NSInteger level8000Hz;
@end


SWIFT_CLASS("_TtC8xFlexAPI8IqStream")
@interface IqStream : NSObject
- (void)requestIqStream;
- (void)requestIqStreamWithIp:(NSString * _Nonnull)ip port:(NSInteger)port;
- (void)removeIqStream:(NSString * _Nonnull)channel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface IqStream (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) NSInteger available;
@property (nonatomic) NSInteger capacity;
@property (nonatomic) NSInteger daxIqChannel;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic) NSInteger port;
@property (nonatomic, copy) NSString * _Nullable pan;
@property (nonatomic) NSInteger rate;
@property (nonatomic, copy) NSString * _Nonnull streamId;
@property (nonatomic) BOOL streaming;
@end


SWIFT_CLASS("_TtC8xFlexAPI6Memory")
@interface Memory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (void)select;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Memory (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) NSInteger digitalLowerOffset;
@property (nonatomic) NSInteger digitalUpperOffset;
@property (nonatomic) NSInteger filterHigh;
@property (nonatomic) NSInteger filterLow;
@property (nonatomic) NSInteger frequency;
@property (nonatomic, copy) NSString * _Nonnull group;
@property (nonatomic, copy) NSString * _Nonnull mode;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger offset;
@property (nonatomic, copy) NSString * _Nonnull offsetDirection;
@property (nonatomic, copy) NSString * _Nonnull owner;
@property (nonatomic) NSInteger rfPower;
@property (nonatomic) NSInteger rttyMark;
@property (nonatomic) NSInteger rttyShift;
@property (nonatomic) BOOL squelchEnabled;
@property (nonatomic) NSInteger squelchLevel;
@property (nonatomic) NSInteger step;
@property (nonatomic, copy) NSString * _Nonnull toneMode;
@property (nonatomic) NSInteger toneValue;
@end


SWIFT_CLASS("_TtC8xFlexAPI14MicAudioStream")
@interface MicAudioStream : NSObject
@property (nonatomic) NSInteger rxLostPacketCount;
- (BOOL)requestMicAudioStream SWIFT_WARN_UNUSED_RESULT;
- (void)removeMicAudioStream;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface MicAudioStream (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) BOOL inUse;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic) NSInteger port;
@property (nonatomic) BOOL radioAck;
@property (nonatomic) NSInteger micGain;
@property (nonatomic, copy) NSString * _Nonnull streamId;
@end


@interface NSNotificationCenter (SWIFT_EXTENSION(xFlexAPI))
/// post a Notification by Name
/// \param notification Notification Name
///
/// \param object associated object
///
+ (void)post:(NSString * _Nonnull)name object:(id _Nullable)object;
/// setup a Notification Observer by Name
/// \param observer the object receiving Notifications
///
/// \param selector a Selector to receive the Notification
///
/// \param type Notification name
///
/// \param object associated object (if any)
///
+ (void)makeObserver:(id _Nonnull)observer with:(SEL _Nonnull)selector of:(NSString * _Nonnull)name object:(id _Nullable)object;
@end


SWIFT_CLASS("_TtC8xFlexAPI4Opus")
@interface Opus : NSObject
/// Send Opus encoded TX audio to the Radio (hardware)
/// \param buffer array of encoded audio samples
///
/// \param samples number of samples to be sent
///
///
/// returns:
/// success / failure
- (BOOL)sendOpusTxAudioWithBuffer:(NSArray<NSNumber *> * _Nonnull)buffer samples:(NSInteger)samples SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Opus (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) BOOL remoteRxOn;
@property (nonatomic) BOOL remoteTxOn;
@property (nonatomic) BOOL rxStreamStopped;
@end

@class Radio;

SWIFT_CLASS("_TtC8xFlexAPI10Panadapter")
@interface Panadapter : NSObject
@property (nonatomic, readonly, weak) Radio * _Nullable radio;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger lastFrameIndex;
@property (nonatomic, readonly) NSInteger droppedPackets;
- (void)requestRfGainInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Panadapter (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull antList;
@property (nonatomic) BOOL autoCenterEnabled;
@property (nonatomic) NSInteger available;
@property (nonatomic) NSInteger average;
@property (nonatomic, copy) NSString * _Nonnull band;
@property (nonatomic) NSInteger bandwidth;
@property (nonatomic) NSInteger capacity;
@property (nonatomic) NSInteger center;
@property (nonatomic) NSInteger daxIqChannel;
@property (nonatomic) NSInteger daxIqRate;
@property (nonatomic) NSInteger fps;
@property (nonatomic) BOOL loopAEnabled;
@property (nonatomic) BOOL loopBEnabled;
@property (nonatomic) NSInteger maxBw;
@property (nonatomic) CGFloat maxDbm;
@property (nonatomic) NSInteger minBw;
@property (nonatomic) CGFloat minDbm;
@property (nonatomic) CGSize panDimensions;
@property (nonatomic, copy) NSString * _Nonnull preamp;
@property (nonatomic) NSInteger rfGain;
@property (nonatomic) NSInteger rfGainHigh;
@property (nonatomic) NSInteger rfGainLow;
@property (nonatomic) NSInteger rfGainStep;
@property (nonatomic, copy) NSString * _Nonnull rfGainValues;
@property (nonatomic, copy) NSString * _Nonnull rxAnt;
@property (nonatomic, copy) NSString * _Nonnull waterfallId;
@property (nonatomic) BOOL weightedAverageEnabled;
@property (nonatomic) BOOL wide;
@property (nonatomic) BOOL wnbEnabled;
@property (nonatomic) NSInteger wnbLevel;
@property (nonatomic) BOOL wnbUpdating;
@property (nonatomic, copy) NSString * _Nonnull xvtrLabel;
@end

@class Tnf;
@class TXAudioStream;

SWIFT_CLASS("_TtC8xFlexAPI5Radio")
@interface Radio : NSObject
@property (nonatomic) BOOL pingerEnabled;
@property (nonatomic, readonly) NSInteger uptime;
@property (nonatomic, readonly, copy) NSString * _Nonnull radioVersion;
@property (nonatomic, readonly, strong) Cwx * _Null_unspecified cwx;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull antennaList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull micList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rfGainList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull sliceList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull sliceErrors;
@property (nonatomic, readonly, copy) NSString * _Nonnull kApiFirmwareSupport;
/// Send a command to the Radio (hardware)
/// \param command a Command String
///
/// \param callback a callback function (if any)
///
- (void)send:(NSString * _Nonnull)command diagnostic:(BOOL)flag replyTo:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Send Vita packet to radio
/// \param data a Vita-49 packet as Data
///
- (void)sendVitaData:(NSData * _Nullable)data;
/// Disconnect the Radio
- (void)disconnect;
- (void)requestAntennaList;
- (void)atuStart;
- (void)atuBypass;
- (AudioStream * _Nonnull)createAudioStream:(NSInteger)channel SWIFT_WARN_UNUSED_RESULT;
- (void)removeAudioStream:(NSString * _Nonnull)streamId;
- (void)createMemory;
- (void)requestMeterList;
- (MicAudioStream * _Nonnull)createMicAudioStream SWIFT_WARN_UNUSED_RESULT;
- (void)removeMicAudioStream:(NSString * _Nonnull)streamId;
- (void)requestMicList;
- (void)startOffset:(BOOL)value;
- (void)createPanafall:(CGSize)dimensions;
- (void)removePanafall:(NSString * _Nonnull)id;
- (void)profileGlobalDelete:(NSString * _Nonnull)name;
- (void)profileGlobalSave:(NSString * _Nonnull)name;
- (void)profileMicDelete:(NSString * _Nonnull)name;
- (void)profileMicSave:(NSString * _Nonnull)name;
- (void)profileTransmitDelete:(NSString * _Nonnull)name;
- (void)profileTransmitSave:(NSString * _Nonnull)name;
- (void)requestRemoteRxAudio:(BOOL)value;
- (void)requestRemoteTxAudio:(BOOL)value;
- (void)requestReboot;
- (void)createSliceWithFrequency:(NSInteger)frequency antenna:(NSString * _Nonnull)antenna mode:(NSString * _Nonnull)mode;
- (void)createSliceWithPanadapter:(Panadapter * _Nonnull)panadapter frequency:(NSInteger)frequency;
- (void)removeSlice:(NSString * _Nonnull)id;
- (void)requestSliceError:(NSString * _Nonnull)id;
- (void)requestSliceList;
- (void)createTnfWithFrequency:(NSInteger)frequency panadapter:(Panadapter * _Nonnull)panadapter;
- (void)removeTnfWithTnf:(Tnf * _Nonnull)tnf;
- (void)setTransmit:(BOOL)value;
- (TXAudioStream * _Nonnull)createTXAudioStream SWIFT_WARN_UNUSED_RESULT;
- (void)removeTXAudioStream:(NSString * _Nonnull)streamId;
- (void)requestUptime;
/// Synchronously find the active Panadapter
///
/// returns:
/// a reference to a Panadapter (or nil)
- (Panadapter * _Nullable)findActivePanadapter SWIFT_WARN_UNUSED_RESULT;
/// Synchronously find the Panadapter for a DaxIqChannel
///
/// returns:
/// a reference to a Panadapter (or nil)
- (Panadapter * _Nullable)findPanadapterByDaxIqChannel:(NSInteger)daxIqChannel SWIFT_WARN_UNUSED_RESULT;
- (IqStream * _Nullable)findIqStreamByDaxIqChannel:(NSInteger)daxIqChannel SWIFT_WARN_UNUSED_RESULT;
/// Disable all TxEnabled
- (void)disableTx;
/// Return references to all Slices on the specified Panadapter
/// \param pan a Panadapter Id
///
///
/// returns:
/// an array of Slices (may be empty)
- (NSArray<Slice *> * _Nonnull)findSlicesOn:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Given a Frequency, return the Slice on the specified Panadapter containing it (if any)
/// \param pan a reference to A Panadapter
///
/// \param freq a Frequency (in hz)
///
///
/// returns:
/// a reference to a Slice (or nil)
- (Slice * _Nullable)findSliceOn:(NSString * _Nonnull)id byFrequency:(NSInteger)freq panafallBandwidth:(NSInteger)panafallBandwidth SWIFT_WARN_UNUSED_RESULT;
/// Return the Active Slice on the specified Panadapter (if any)
/// \param pan a reference to a Panadapter
///
///
/// returns:
/// a Slice (or nil)
- (Slice * _Nullable)findActiveSliceOn:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (Slice * _Nullable)findSliceByDaxChannel:(NSInteger)channel SWIFT_WARN_UNUSED_RESULT;
/// Given a Frequency, return a reference to the Tnf containing it (if any)
/// \param freq a Frequency (in hz)
///
///
/// returns:
/// a reference to a Tnf (or nil)
- (Tnf * _Nullable)findTnfByFrequency:(NSInteger)freq panafallBandwidth:(NSInteger)panafallBandwidth SWIFT_WARN_UNUSED_RESULT;
/// Given a Memory Id, return a reference to the Memory
/// \param memoryId the ID of a Meter
///
///
/// returns:
/// a reference to a Memory
- (Memory * _Nullable)findMemoryByMemoryId:(NSString * _Nonnull)memoryId SWIFT_WARN_UNUSED_RESULT;
/// Add a Memory to the Memories collection
/// \param memory a reference to a Memory
///
- (void)addMemory:(Memory * _Nonnull)memory;
/// Remove a Memory from the Memories collection
/// \param memory a reference to a Memory
///
- (void)removeMemory:(Memory * _Nonnull)memory;
/// Process the Reply to a command, reply format: <value>,<value>,…<value>
/// \param command the original command
///
/// \param seqNum the Sequence Number of the original command
///
/// \param responseValue the response value
///
/// \param reply the reply
///
- (void)replyHandler:(NSString * _Nonnull)command seqNum:(NSString * _Nonnull)seqNum responseValue:(NSString * _Nonnull)responseValue reply:(NSString * _Nonnull)reply;
/// Process a sent message
/// \param text text of the command
///
- (void)sentMessage:(NSString * _Nonnull)text;
/// Process a received message
/// \param text text received from the Radio
///
- (void)receivedMessage:(NSString * _Nonnull)text;
/// Respond to a TCP Connection/Disconnection event
/// \param connected stae of connection
///
- (void)tcpStateWithConnected:(BOOL)connected host:(NSString * _Nonnull)host port:(uint16_t)port error:(NSString * _Nonnull)error;
/// Receive an Error message from TCP Manager
/// \param message the message
///
- (void)tcpError:(NSString * _Nonnull)message;
/// Respond to a UDP Connection/Disconnection event
/// \param connected state of binding
///
- (void)udpStateWithBound:(BOOL)bound port:(uint16_t)port error:(NSString * _Nonnull)error;
/// Receive a State Change message from UDP Manager
/// \param message the state
///
- (void)udpStreamWithActive:(BOOL)active;
/// Receive an Error message from UDP Manager
/// \param message the message
///
- (void)udpError:(NSString * _Nonnull)message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class Waterfall;

@interface Radio (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) BOOL accTxEnabled;
@property (nonatomic) NSInteger accTxDelay;
@property (nonatomic) BOOL accTxReqEnabled;
@property (nonatomic) BOOL accTxReqPolarity;
@property (nonatomic) BOOL apfEnabled;
@property (nonatomic) NSInteger apfQFactor;
@property (nonatomic) NSInteger apfGain;
@property (nonatomic) BOOL atuPresent;
@property (nonatomic, copy) NSString * _Nonnull atuStatus;
@property (nonatomic) BOOL atuEnabled;
@property (nonatomic) BOOL atuMemoriesEnabled;
@property (nonatomic) BOOL atuUsingMemories;
@property (nonatomic) NSInteger availablePanadapters;
@property (nonatomic) NSInteger availableSlices;
@property (nonatomic) BOOL bandPersistenceEnabled;
@property (nonatomic) BOOL binauralRxEnabled;
@property (nonatomic) NSInteger calFreq;
@property (nonatomic, copy) NSString * _Nonnull callsign;
@property (nonatomic) NSInteger carrierLevel;
@property (nonatomic, copy) NSString * _Nonnull chassisSerial;
@property (nonatomic) BOOL companderEnabled;
@property (nonatomic) NSInteger companderLevel;
@property (nonatomic, copy) NSString * _Nonnull currentGlobalProfile;
@property (nonatomic, copy) NSString * _Nonnull currentMicProfile;
@property (nonatomic, copy) NSString * _Nonnull currentTxProfile;
@property (nonatomic) BOOL cwAutoSpaceEnabled;
@property (nonatomic) BOOL cwBreakInEnabled;
@property (nonatomic) NSInteger cwBreakInDelay;
@property (nonatomic) BOOL cwIambicEnabled;
@property (nonatomic) NSInteger cwIambicMode;
@property (nonatomic) BOOL cwlEnabled;
@property (nonatomic) NSInteger cwPitch;
@property (nonatomic) BOOL cwSidetoneEnabled;
@property (nonatomic) BOOL cwSwapPaddles;
@property (nonatomic) BOOL cwSyncCwxEnabled;
@property (nonatomic) NSInteger cwWeight;
@property (nonatomic) NSInteger cwSpeed;
@property (nonatomic) BOOL daxEnabled;
@property (nonatomic) NSInteger daxIqAvailable;
@property (nonatomic) NSInteger daxIqCapacity;
@property (nonatomic) BOOL enforcePrivateIpEnabled;
@property (nonatomic) NSInteger filterCwAutoLevel;
@property (nonatomic) NSInteger filterDigitalAutoLevel;
@property (nonatomic) NSInteger filterVoiceAutoLevel;
@property (nonatomic) NSInteger filterCwLevel;
@property (nonatomic) NSInteger filterDigitalLevel;
@property (nonatomic) NSInteger filterVoiceLevel;
@property (nonatomic, copy) NSString * _Nonnull fpgaMbVersion;
@property (nonatomic) NSInteger freqErrorPpb;
@property (nonatomic) NSInteger frequency;
@property (nonatomic) BOOL fullDuplexEnabled;
@property (nonatomic, copy) NSString * _Nonnull gateway;
@property (nonatomic, copy) NSString * _Nonnull gpsAltitude;
@property (nonatomic) double gpsFrequencyError;
@property (nonatomic, copy) NSString * _Nonnull gpsStatus;
@property (nonatomic, copy) NSString * _Nonnull gpsGrid;
@property (nonatomic, copy) NSString * _Nonnull gpsLatitude;
@property (nonatomic, copy) NSString * _Nonnull gpsLongitude;
@property (nonatomic) BOOL gpsPresent;
@property (nonatomic, copy) NSString * _Nonnull gpsSpeed;
@property (nonatomic, copy) NSString * _Nonnull gpsTime;
@property (nonatomic) double gpsTrack;
@property (nonatomic) BOOL gpsTracked;
@property (nonatomic) BOOL gpsVisible;
@property (nonatomic) NSInteger headphoneGain;
@property (nonatomic) BOOL headphoneMute;
@property (nonatomic) BOOL hwAlcEnabled;
@property (nonatomic) BOOL inhibit;
@property (nonatomic, copy) NSString * _Nonnull ipAddress;
@property (nonatomic, copy) NSString * _Nonnull location;
@property (nonatomic, copy) NSString * _Nonnull macAddress;
@property (nonatomic) NSInteger lineoutGain;
@property (nonatomic) BOOL lineoutMute;
@property (nonatomic) NSInteger maxPowerLevel;
@property (nonatomic) BOOL metInRxEnabled;
@property (nonatomic) BOOL micAccEnabled;
@property (nonatomic) BOOL micBiasEnabled;
@property (nonatomic) BOOL micBoostEnabled;
@property (nonatomic) NSInteger micLevel;
@property (nonatomic, copy) NSString * _Nonnull micSelection;
@property (nonatomic) BOOL monAvailable;
@property (nonatomic) NSInteger monGainCw;
@property (nonatomic) NSInteger monGainSb;
@property (nonatomic) NSInteger monPanCw;
@property (nonatomic) NSInteger monPanSb;
@property (nonatomic, copy) NSString * _Nonnull netmask;
@property (nonatomic, copy) NSString * _Nonnull nickname;
@property (nonatomic) NSInteger numberOfScus;
@property (nonatomic) NSInteger numberOfSlices;
@property (nonatomic) NSInteger numberOfTx;
@property (nonatomic, copy) NSString * _Nonnull psocMbPa100Version;
@property (nonatomic, copy) NSString * _Nonnull psocMbtrxVersion;
@property (nonatomic, copy) NSString * _Nonnull radioModel;
@property (nonatomic, copy) NSString * _Nonnull radioOptions;
@property (nonatomic, copy) NSString * _Nonnull radioScreenSaver;
@property (nonatomic) BOOL rawIqEnabled;
@property (nonatomic) BOOL rcaTxReqEnabled;
@property (nonatomic) BOOL rcaTxReqPolarity;
@property (nonatomic, copy) NSString * _Nonnull reason;
@property (nonatomic, copy) NSString * _Nonnull region;
@property (nonatomic) BOOL remoteOnEnabled;
@property (nonatomic) NSInteger rfPower;
@property (nonatomic) NSInteger rttyMark;
@property (nonatomic) BOOL sbMonitorEnabled;
@property (nonatomic, copy) NSString * _Nonnull smartSdrMB;
@property (nonatomic) BOOL snapTuneEnabled;
@property (nonatomic, copy) NSString * _Nonnull softwareVersion;
@property (nonatomic, copy) NSString * _Nonnull source;
@property (nonatomic) BOOL speechProcessorEnabled;
@property (nonatomic) NSInteger speechProcessorLevel;
@property (nonatomic) BOOL ssbPeakControlEnabled;
@property (nonatomic) BOOL startOffset;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull staticGateway;
@property (nonatomic, copy) NSString * _Nonnull staticIp;
@property (nonatomic, copy) NSString * _Nonnull staticNetmask;
@property (nonatomic) NSInteger timeout;
@property (nonatomic) BOOL tnfEnabled;
@property (nonatomic) BOOL tune;
@property (nonatomic) NSInteger tunePower;
@property (nonatomic) BOOL txEnabled;
@property (nonatomic) NSInteger txDelay;
@property (nonatomic) BOOL txFilterChanges;
@property (nonatomic) NSInteger txFilterHigh;
@property (nonatomic) NSInteger txFilterLow;
@property (nonatomic) BOOL txInWaterfallEnabled;
@property (nonatomic) BOOL txRfPowerChanges;
@property (nonatomic) BOOL tx1Enabled;
@property (nonatomic) NSInteger tx1Delay;
@property (nonatomic) BOOL tx2Enabled;
@property (nonatomic) NSInteger tx2Delay;
@property (nonatomic) BOOL tx3Enabled;
@property (nonatomic) NSInteger tx3Delay;
@property (nonatomic) BOOL voxEnabled;
@property (nonatomic) NSInteger voxDelay;
@property (nonatomic) NSInteger voxLevel;
@property (nonatomic, copy) NSString * _Nonnull waveformList;
@property (nonatomic, copy) NSDictionary<NSString *, AudioStream *> * _Nonnull audioStreams;
@property (nonatomic, copy) NSDictionary<NSString *, IqStream *> * _Nonnull iqStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Memory *> * _Nonnull memories;
@property (nonatomic, copy) NSDictionary<NSString *, MicAudioStream *> * _Nonnull micAudioStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Opus *> * _Nonnull opusStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Panadapter *> * _Nonnull panadapters;
@property (nonatomic, copy) NSDictionary<NSString *, Slice *> * _Nonnull slices;
@property (nonatomic, copy) NSDictionary<NSString *, Tnf *> * _Nonnull tnfs;
@property (nonatomic, copy) NSDictionary<NSString *, TXAudioStream *> * _Nonnull txAudioStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Waterfall *> * _Nonnull waterfalls;
@property (nonatomic) uint16_t _udpPort;
@end

@class GCDAsyncUdpSocket;

SWIFT_CLASS("_TtC8xFlexAPI12RadioFactory")
@interface RadioFactory : NSObject <GCDAsyncUdpSocketDelegate>
/// Initialize a RadioFactory
/// \param discoveryPort port number
///
/// \param checkInterval how often to check
///
/// \param notSeenInterval timeout interval
///
- (nonnull instancetype)initWithDiscoveryPort:(uint16_t)discoveryPort checkInterval:(NSTimeInterval)checkInterval notSeenInterval:(NSTimeInterval)notSeenInterval OBJC_DESIGNATED_INITIALIZER;
/// send a Notification containing a list of current radios
- (void)updateAvailableRadios;
/// The Socket received data
/// \param sock the GCDAsyncUdpSocket
///
/// \param data the Data received
///
/// \param address the Address of the sender
///
/// \param filterContext the FilterContext
///
- (void)udpSocket:(GCDAsyncUdpSocket * _Nonnull)sock didReceiveData:(NSData * _Nonnull)data fromAddress:(NSData * _Nonnull)address withFilterContext:(id _Nullable)filterContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8xFlexAPI5Slice")
@interface Slice : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// Initialize a Slice
/// \param radio parent Radio class
///
/// \param sliceId a Slice Id
///
/// \param queue Slice concurrent queue
///
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio sliceId:(NSString * _Nonnull)sliceId queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (void)setRecord:(BOOL)value;
- (void)setPlay:(BOOL)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Slice (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) BOOL active;
@property (nonatomic, copy) NSString * _Nonnull agcMode;
@property (nonatomic) NSInteger agcOffLevel;
@property (nonatomic) NSInteger agcThreshold;
@property (nonatomic) BOOL anfEnabled;
@property (nonatomic) NSInteger anfLevel;
@property (nonatomic) BOOL apfEnabled;
@property (nonatomic) NSInteger apfLevel;
@property (nonatomic) NSInteger audioGain;
@property (nonatomic) BOOL audioMute;
@property (nonatomic) NSInteger audioPan;
@property (nonatomic) BOOL autoPanEnabled;
@property (nonatomic) NSInteger daxChannel;
@property (nonatomic) NSInteger daxClients;
@property (nonatomic) BOOL daxTxEnabled;
@property (nonatomic) BOOL dfmPreDeEmphasisEnabled;
@property (nonatomic) NSInteger digitalLowerOffset;
@property (nonatomic) NSInteger digitalUpperOffset;
@property (nonatomic) BOOL diversityChild;
@property (nonatomic) BOOL diversityEnabled;
@property (nonatomic) NSInteger diversityIndex;
@property (nonatomic) BOOL diversityParent;
@property (nonatomic) NSInteger filterHigh;
@property (nonatomic) NSInteger filterLow;
@property (nonatomic) NSInteger fmDeviation;
@property (nonatomic) float fmRepeaterOffset;
@property (nonatomic) BOOL fmToneBurstEnabled;
@property (nonatomic) float fmToneFreq;
@property (nonatomic, copy) NSString * _Nonnull fmToneMode;
@property (nonatomic) NSInteger frequency;
@property (nonatomic) BOOL inUse;
@property (nonatomic) BOOL locked;
@property (nonatomic) BOOL loopAEnabled;
@property (nonatomic) BOOL loopBEnabled;
@property (nonatomic, copy) NSString * _Nonnull mode;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull modeList;
@property (nonatomic) BOOL nbEnabled;
@property (nonatomic) NSInteger nbLevel;
@property (nonatomic) BOOL nrEnabled;
@property (nonatomic) NSInteger nrLevel;
@property (nonatomic) NSInteger owner;
@property (nonatomic, copy) NSString * _Nonnull panadapterId;
@property (nonatomic) BOOL playbackEnabled;
@property (nonatomic) BOOL postDemodBypassEnabled;
@property (nonatomic) NSInteger postDemodHigh;
@property (nonatomic) NSInteger postDemodLow;
@property (nonatomic) BOOL qskEnabled;
@property (nonatomic) BOOL recordEnabled;
@property (nonatomic) float recordLength;
@property (nonatomic, copy) NSString * _Nonnull repeaterOffsetDirection;
@property (nonatomic) NSInteger rfGain;
@property (nonatomic) BOOL ritEnabled;
@property (nonatomic) NSInteger ritOffset;
@property (nonatomic) NSInteger rttyMark;
@property (nonatomic) NSInteger rttyShift;
@property (nonatomic, copy) NSString * _Nonnull rxAnt;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull rxAntList;
@property (nonatomic) NSInteger step;
@property (nonatomic, copy) NSString * _Nonnull stepList;
@property (nonatomic) BOOL squelchEnabled;
@property (nonatomic) NSInteger squelchLevel;
@property (nonatomic, copy) NSString * _Nonnull txAnt;
@property (nonatomic) BOOL txEnabled;
@property (nonatomic) float txOffsetFreq;
@property (nonatomic) BOOL wide;
@property (nonatomic) BOOL wnbEnabled;
@property (nonatomic) NSInteger wnbLevel;
@property (nonatomic) BOOL xitEnabled;
@property (nonatomic) NSInteger xitOffset;
@end


SWIFT_CLASS("_TtC8xFlexAPI13TXAudioStream")
@interface TXAudioStream : NSObject
- (BOOL)requestTXAudioStream SWIFT_WARN_UNUSED_RESULT;
- (void)removeTXAudioStream;
- (BOOL)sendTXAudioWithLeft:(NSArray<NSNumber *> * _Nonnull)left right:(NSArray<NSNumber *> * _Nonnull)right samples:(NSInteger)samples SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface TXAudioStream (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) BOOL inUse;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic) NSInteger port;
@property (nonatomic) BOOL radioAck;
@property (nonatomic) BOOL transmit;
@property (nonatomic) NSInteger txGain;
@property (nonatomic, copy) NSString * _Nonnull streamId;
@end

@class GCDAsyncSocket;

SWIFT_CLASS("_TtC8xFlexAPI10TcpManager")
@interface TcpManager : NSObject <GCDAsyncSocketDelegate>
/// Disconnect from the Radio (hardware)
- (void)disconnect;
/// Send a Command to the Radio (hardware), optionally register to be Notified upon receipt of a Reply
/// \param cmd a Command string
///
/// \param diagnostic whether to add “D” suffix
///
/// \param replyTo ReplyHandler (if any)
///
///
/// returns:
/// the Sequence Number of the Command
- (NSInteger)send:(NSString * _Nonnull)cmd diagnostic:(BOOL)diagnostic replyTo:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Read the next data block (with an indefinite timeout)
- (void)readNext;
/// Called when the TCP/IP connection has been disconnected
/// \param sock the disconnected socket
///
/// \param err the error
///
- (void)socketDidDisconnect:(GCDAsyncSocket * _Nonnull)sock withError:(NSError * _Nullable)err;
/// Called after the TCP/IP connection has been established
/// \param sock the socket
///
/// \param host the host
///
/// \param port the port
///
- (void)socket:(GCDAsyncSocket * _Nonnull)sock didConnectToHost:(NSString * _Nonnull)host port:(uint16_t)port;
/// Called when data has been read from the TCP/IP connection
/// \param sock the socket data was received on
///
/// \param data the Data
///
/// \param tag the Tag associated with this receipt
///
- (void)socket:(GCDAsyncSocket * _Nonnull)sock didReadData:(NSData * _Nonnull)data withTag:(NSInteger)tag;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8xFlexAPI3Tnf")
@interface Tnf : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger minWidth;
@property (nonatomic) NSInteger maxWidth;
/// Initialize a Tnf
/// \param id a Tnf Id
///
/// \param radio parent Radio class
///
/// \param queue Tnf Concurrent queue
///
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id radio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue;
/// Initialize a Tnf
/// \param id a Tnf Id
///
/// \param radio parent Radio class
///
/// \param frequency Tnf frequency (Hz)
///
/// \param queue Tnf Concurrent queue
///
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id radio:(Radio * _Nonnull)radio frequency:(NSInteger)frequency queue:(dispatch_queue_t _Nonnull)queue;
/// Initialize a Tnf
/// \param id a Tnf Id
///
/// \param radio parent Radio class
///
/// \param frequency Tnf frequency (Hz)
///
/// \param depth a Depth value
///
/// \param width a Width value
///
/// \param permanent true = permanent
///
/// \param queue Tnf Concurrent queue
///
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id radio:(Radio * _Nonnull)radio frequency:(NSInteger)frequency depth:(NSInteger)depth width:(NSInteger)width permanent:(BOOL)permanent queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Tnf (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) NSInteger depth;
@property (nonatomic) NSInteger frequency;
@property (nonatomic) BOOL permanent;
@property (nonatomic) NSInteger width;
@end


SWIFT_CLASS("_TtC8xFlexAPI10UdpManager")
@interface UdpManager : NSObject <GCDAsyncUdpSocketDelegate>
@property (nonatomic, readonly) uint16_t port;
@property (nonatomic, readonly) BOOL canBroadcast;
/// Send a Broadcast
/// \param data a Vita-49 packet as Data
///
- (void)sendBroadcastWithData:(NSData * _Nonnull)data;
/// Send Vita packet to radio
/// \param data a Vita-49 packet as Data
///
- (void)sendData:(NSData * _Nonnull)data;
/// Bind to the UDP Port
- (void)bind;
- (void)beginReceiving;
/// Unbind from the UDP port
- (void)unbind;
/// Called when data has been read from the UDP connection
/// \param sock the receiving socket
///
/// \param data the data received
///
/// \param address the Host address
///
/// \param filterContext a filter context (if any)
///
- (void)udpSocket:(GCDAsyncUdpSocket * _Nonnull)sock didReceiveData:(NSData * _Nonnull)data fromAddress:(NSData * _Nonnull)address withFilterContext:(id _Nullable)filterContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8xFlexAPI9Waterfall")
@interface Waterfall : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger lastTimecode;
@property (nonatomic, readonly) NSInteger droppedPackets;
@property (nonatomic, readonly) BOOL isBeingRemoved;
/// Initialize a Waterfall
/// \param streamId a Waterfall Id
///
/// \param radio parent Radio class
///
/// \param queue Waterfall Concurrent queue
///
- (nonnull instancetype)initWithStreamId:(NSString * _Nonnull)streamId radio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Waterfall (SWIFT_EXTENSION(xFlexAPI))
@property (nonatomic) BOOL autoBlackEnabled;
@property (nonatomic) uint32_t autoBlackLevel;
@property (nonatomic) NSInteger blackLevel;
@property (nonatomic) NSInteger colorGain;
@property (nonatomic) NSInteger gradientIndex;
@property (nonatomic) NSInteger lineDuration;
@property (nonatomic, copy) NSString * _Nonnull panadapterId;
@end

#pragma clang diagnostic pop
